<?php

namespace AppBundle\Repository;

/**
 * AttachmentTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachmentTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
