<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Attachment;

/**
 * AttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachmentRepository extends \Doctrine\ORM\EntityRepository
{

    public function getNew(array $attachment) {
        $att = new Attachment();
        return $att
            ->setName($attachment['name'])
            ->setAuthor($attachment['author'])
            ->setType($attachment['type'])
            ->setParameters(json_encode([
                'body' => $attachment['body'],
            ]))
        ;
    }



}
