<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Comment;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param string $entity
     * @param int $entityId
     * @return ArrayCollection
     */
    public function getEntityComments(string $entity, int $entityId) : ArrayCollection
    {
        return $this->getEntityManager()->getRepository($entity)
            ->find($entityId)
            ->getComments()
            ->map(function(Comment $item) {
                return $item->toArray();
            });
    }

    /**
     * @param Comment $comment
     * @param string $entity
     * @param int $entityId
     * @return array
     */
    public function addEntityComment(Comment $comment, string $entity,  int $entityId) : array
    {
        $this->getEntityManager()->persist($this->getEntityManager()->getRepository($entity)
            ->find($entityId)
            ->addComment($comment));
        $this->getEntityManager()->flush();
        $this->getEntityManager()->clear();
        return $comment->toArray();
    }
}
