<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * FollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFollowers(User $user) {
        $res = $this->findBy([
            'following' => $user
        ]);
        $return = [];
        foreach ($res as $follow) {
            $return[] = $follow->getFollower();
        }
        return $return;
    }
}
