<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * FollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FollowRepository extends \Doctrine\ORM\EntityRepository
{

}
