<?php

namespace AppBundle\Repository;

/**
 * PublicationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
