api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /api/login_check
    defaults: { _controller: "AppBundle:Security:check" }
    requirements:
        _method: POST

app_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"

api_bundle:
    type: rest
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix: api
    defaults : {_format: json}