app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_login_check:
    path: /api/login_check
    defaults: { _controller: "AppBundle:Security:check" }
    requirements:
        _method: POST

app_bundle:
   resource: "@AppBundle/Resources/config/routing.yml"
