# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login_check:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                #provider: fos_userbundle
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                username_parameter: _username
                password_parameter: _password

        avatar:
            pattern: avatar$
            security: false
        api:
              provider: fos_userbundle
              pattern: ^/api
              stateless: true
              lexik_jwt:
                  authorization_header:
                      enabled: true
                      prefix:  Bearer
                  query_parameter:
                      enabled: true
                      name: bearer
              guard:
                  authenticators:
                      - lexik_jwt_authentication.jwt_token_authenticator

        main:
           pattern: ^/
           form_login:
               provider: fos_userbundle
               check_path: /login_check
               login_path: /login
           logout:
               path:    /logout
               target: /
              # provider: fos_userbundle
              # csrf_provider: form.csrf_provider

           anonymous:    true

            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/initapi, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }

    encoders:
       FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
       ROLE_ADMIN:       ROLE_USER
       ROLE_SUPER_ADMIN: ROLE_ADMIN

