api_rest_users:
    type:     rest
    resource: ApiBundle\Controller\rest\UsersController
api_rest_attachments_type:
    type:     rest
    resource: ApiBundle\Controller\rest\AttachmentTypesController
api_rest_attachments:
    type:     rest
    resource: ApiBundle\Controller\rest\AttachmentsController
api_rest_publications:
    type:     rest
    resource: ApiBundle\Controller\rest\PublicationsController
api_rest_publicationtypes:
    type:     rest
    resource: ApiBundle\Controller\rest\PublicationTypesController
api_rest_comments:
    type:     rest
    resource: ApiBundle\Controller\rest\CommentsController