api_default:
    path:  /default
    defaults: { _controller: "ApiBundle:Default:index" }

api_playlist_get:
    path:  /playlist
    defaults: { _controller: "ApiBundle:PlayList:get" }
    methods : [GET]

api_playlist_set:
    path:  /playlist
    defaults: { _controller: "ApiBundle:PlayList:set" }
    methods : [PUT]

# Publication type
api_publication_type_set:
    path:  /publications/type
    defaults: { _controller: "ApiBundle:PublicationType:put" }
    methods : [PUT]
api_publication_type_get:
    path:  /publications/type
    defaults: { _controller: "ApiBundle:PublicationType:get" }
    methods : [GET]
api_publication_type_delete:
    path:  /publications/type
    defaults: { _controller: "ApiBundle:PublicationType:delete" }
    methods : [DELETE]

# Publications
api_publication_set:
    path:  /publications
    defaults: { _controller: "ApiBundle:Publication:put" }
    methods : [PUT]
api_publication_get:
    path:  /publications
    defaults: { _controller: "ApiBundle:Publication:get" }
    methods : [GET]
api_publication_delete:
    path:  /publications
    defaults: { _controller: "ApiBundle:Publication:delete" }
    methods : [DELETE]

# Attachment
api_attachement_set:
    path:  /attachments
    defaults: { _controller: "ApiBundle:Attachment:put" }
    methods : [PUT]
api_attachement_get:
    path:  /attachments
    defaults: { _controller: "ApiBundle:Attachment:get" }
    methods : [GET]
api_attachement_delete:
    path:  /attachments
    defaults: { _controller: "ApiBundle:Attachment:delete" }
    methods : [DELETE]

# User
api_publication_type_set:
    path:  /users
    defaults: { _controller: "ApiBundle:User:put" }
    methods : [PUT]
# User Follow
api_follower_set:
    path:  /users/{user}/followers
    defaults: { _controller: "ApiBundle:Follow:putFollowers", user: 0 }
    requirements:
        user: '\d+'
    methods : [PUT]
api_follower_get:
    path:  /users/{user}/followers
    defaults: { _controller: "ApiBundle:Follow:getFollowers", user: 0 }
    requirements:
        user: '\d+'
    methods : [GET]
api_following_get:
    path:  /users/{user}/followings
    defaults: { _controller: "ApiBundle:Follow:getFollowings", user: 0 }
    requirements:
        user: '\d+'
    methods : [GET]
api_following_delete:
    path:  /users/{user}/followings
    defaults: { _controller: "ApiBundle:Follow:deleteFollowings", user: 0 }
    requirements:
        user: '\d+'
    methods : [delete]
# User Publications
api_user_publications_get:
    path:  /users/{user}/publications
    defaults: { _controller: "ApiBundle:UserPublications:get" }
    methods : [GET]
    requirements:
        user: '\d+'
# User Avatar
api_user_avatar_set:
    path:  /users/{user}/avatar
    defaults: { _controller: "ApiBundle:UserAvatar:put" }
    methods : [PUT]
    requirements:
        user: '\d+'
api_user_avatar_get:
    path:  /users/{user}/avatar
    defaults: { _controller: "ApiBundle:UserAvatar:get" }
    methods : [GET]
    requirements:
        user: '\d+'

# TimeLine
api_timeline_get:
    path:  /timelines
    defaults: { _controller: "ApiBundle:TimeLine:get" }
    methods : [GET]

api_timeline_set:
    path:  /timelines
    defaults: { _controller: "ApiBundle:TimeLine:set" }
    methods : [PUT]
