services:
    api.service:
        class:     ApiBundle\Services\ApiService
        autowire: true
    api.attachement:
        class:     ApiBundle\Services\AttachmentService
        autowire: true
    api.comment:
        class:     ApiBundle\Services\CommentService
        autowire: true
